<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumCustomization extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['color__main', 'color__second', 'color__background', 'forum__description_tooltip', 'forum__icon__default', 'user__profile__tooltip', 'user__profile__avatar', 'updated_at'];
    protected $table = 'forum__customization';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
