<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumRanks extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['default', 'name', 'background', 'staff', 'color', 'updated_at'];
    protected $table = 'forum__ranks';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }


}
