<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumForum extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['position', 'forum_id', 'category', 'size', 'name', 'description', 'write__rank_id', 'watch__rank_id', 'icon_type', 'icon', 'updated_at'];
    protected $table = 'forum__forum';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
