<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumThread extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['forum_id', 'name', 'message', 'pin', 'tags', 'lock', 'archive', 'delete', 'updated_at'];
    protected $table = 'forum__thread';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

}
