<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumWidgetShare extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['name', 'icon_type', 'icon', 'color', 'updated_at'];
    protected $table = 'forum__widget__share';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
