<?php

namespace Extensions\Plugins\Forum_arckene__421339390\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class ForumThreadReport extends Model
{
    use CacheQueryBuilder;

    protected $fillable = ['archive', 'updated_at'];
    protected $table = 'forum__thread_report';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
